### product
GET http://localhost:3000/api/v1/product HTTP/1.1

### transaction
GET http://localhost:3000/transaction HTTP/1.1

### login
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{"username":"lek", "password":"555"}